apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-todo-deployment
  namespace: django-todo-ns
  labels:
    app: django-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-todo
  template:
    metadata:
      labels:
        app: django-todo
    spec:
      containers:
      - name: django-todo
        image: iamamash/django-todo-cicd:latest
        ports:
        - containerPort: 8000
        volumeMounts:
            - name: django-volume
              mountPath: /app
      volumes:
        - name: django-volume
          persistentVolumeClaim:
            claimName: pvc-todo-app
