apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-todo-app
  namespace: django-todo-ns
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/ubuntu/volume"
