apiVersion: v1
kind: Service
metadata:
  name: django-todo-service
  namespace: django-todo-ns
spec:
  type: NodePort
  selector:
    app: django-todo
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30007
